name: lindenmayer_systems
description: A Dart library to handle generative grammars known as L-Systems (Lindenmayer Systems).
version: 0.0.5
homepage: https://github.com/gildurao/lindenmayer-systems

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
